language: node_js
node_js:
  - 10
  - 12
  - 13
jobs:
  - include:
    - stage: update mirror
      node_js: 12
      if: branch = master AND type = cron AND os = linux
      script: ./scripts/ci-cron
