#!/bin/bash

echo "Before:"
du -sh .git

git filter-repo --invert-paths --path-glob "redist/*.tar.gz" --force
git for-each-ref --format="delete %(refname)" refs/original | git update-ref --stdin
git reflog expire --expire=now --all
git gc --prune=now

echo "After:"
du -sh .git
