name: Databases Updater

on:
  schedule:
    - cron: '0 1 27 * *'
  workflow_dispatch:

jobs:
  update_dbs:
    name: Update MaxMind databases in redistribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/ci-cron
        env:
          GITHUB_PUSH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
